import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';

const roboto = Roboto({
	weight: ['400', '500', '700'],
	subsets: ['latin'],
	preload: true,
});

export const metadata: Metadata = {
	title: 'Historic Social',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={roboto.className}>{children}</body>
			</html>
		</ClerkProvider>
	);
}
