import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Navbar from './component/header/navbar';
import LeftSide from './component/leftside/left-side';
import RightSide from './component/rightside/right-side';

// const roboto = Roboto({
// 	weight: ['400', '500', '700'],
// 	subsets: ['latin'],
// 	preload: true,
// });

export const metadata: Metadata = {
	title: 'Historic Social',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang='en'>
				{/*  className={roboto.className}> */}
				<body>
					<Navbar />
					<div className='grid grid-cols-12 w-full lg:px-16 md:px-8 px-3 py-5 bg-slate-100 min-h-screen container m-auto '>
						<div className=' lg:col-span-2 hidden lg:flex'>
							<LeftSide />
						</div>
						<div className='col-span-12 md:col-span-8 lg:col-span-7'>
							{children}
						</div>
						<div className=' md:col-span-4 lg:col-span-3  hidden md:flex'>
							<RightSide />
						</div>
					</div>
				</body>
			</html>
		</ClerkProvider>
	);
}
